In [20]:
from __future__ import print_function
import cPickle as pickle

In [60]:
whole_data = np.array(pickle.load(open('./result_vector.p')) ).reshape(-1,6)

In [21]:
x = pickle.load(open('./result_vector.p')) 

In [22]:
x

[[[0.6549846024623855,
   0.7142857142857143,
   0.71554252199413482,
   0.6240409207161125,
   0.7559322033898305,
   0.7934426229508196]],
 [[0.6549846024623855,
   0.7142857142857143,
   0.71554252199413482,
   0.6240409207161125,
   0.7559322033898305,
   0.7934426229508196]],
 [[0.6549846024623855,
   0.7142857142857143,
   0.71554252199413482,
   0.6240409207161125,
   0.7559322033898305,
   0.7934426229508196]],
 [[0.6549846024623855,
   0.75,
   0.71554252199413482,
   0.73317307692307687,
   0.7559322033898305,
   0.9498207885304659]],
 [[0.7142857142857143,
   0.75,
   0.6240409207161125,
   0.73317307692307687,
   0.7934426229508196,
   0.9498207885304659]],
 [[0.7142857142857143,
   0.75,
   0.6240409207161125,
   0.73317307692307687,
   0.7934426229508196,
   0.9498207885304659]],
 [[0.7142857142857143,
   0.75,
   0.6240409207161125,
   0.73317307692307687,
   0.7934426229508196,
   0.9498207885304659]],
 [[0.40625,
   0.4322791477197249,
   0.35691489361702128,
   0.3769

In [27]:
y = []
with open('./data/dev.answers', 'rb') as f:
    for true_val in f.readlines():
        y.append(int(true_val))

In [28]:
y

[-1,
 -1,
 -1,
 -1,
 0,
 0,
 0,
 -1,
 -1,
 -1,
 0,
 -1,
 -1,
 1,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 0,
 1,
 1,
 1,
 1,
 0,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 1,
 -1,
 -1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 -1,
 -1,
 0,
 -1,
 -1,
 -1,
 -1,
 0,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 -1,
 0,
 -1,
 1,
 1,
 -1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 -1,
 -1,
 -1,
 -1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 -1,
 -1,
 -1,
 -1,
 0,
 -1,
 1,
 -1,
 1,
 1,
 -1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 -1,
 -1,
 1,
 -1,
 0,
 -1,
 -1,
 -1,
 -1,
 1,
 0,
 -1,
 -1,
 0,
 -1,
 0,
 1,
 0,
 1,
 -1,
 0,
 1,
 0,
 0,
 -1,
 -1,
 0,
 -1,
 -1,
 -1,
 -1,
 0,
 1,
 0,
 1,
 1,
 -1,
 -1,
 0,
 1,
 1,
 1,
 -1,
 1,
 0,
 -1,
 1,
 1,
 1,
 -1,
 -1,
 -1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 -1,
 -1,
 1,
 1,
 1,
 1,
 -1,
 -1,
 -1,
 0,
 -1,
 -1,
 1,
 1,
 1,
 0,
 -1,
 0,
 -1,
 1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 0,
 -1,
 -1,
 -1,
 -1,
 0,
 0,

# Convert to Numpy arrays and set up for training

In [29]:
from sklearn.model_selection import train_test_split

In [34]:
import numpy as np

In [38]:
x = x[0:len(y)]

In [39]:
len(x)

25568

In [40]:
len(y)

25568

In [47]:
x_train, x_test, y_train, y_test = train_test_split(np.array(x).reshape(-1, 6), np.array(y).reshape(-1,1), test_size=0.05)

In [48]:
x_train.shape

(24289, 6)

In [49]:
y_train.shape

(24289, 1)

In [50]:
x_test.shape

(1279, 6)

In [51]:
y_test.shape

(1279, 1)

# Start applying machine learning

## Logistic Regression

In [90]:
from sklearn.linear_model import LogisticRegression, LogisticRegressionCV, RidgeClassifierCV
from sklearn.metrics import accuracy_score, classification_report

In [93]:
log = LogisticRegression(penalty='l2', 
                   dual=False, tol=0.0001, 
                   C=1.0, fit_intercept=True, 
                   intercept_scaling=1, class_weight=None, 
                   random_state=None, solver='saga', 
                   max_iter=1000, multi_class='multinomial', verbose=0, 
                   warm_start=False, n_jobs=1)

In [94]:
log.fit(x_train, y_train)
pred = log.predict(x_test)
acc = accuracy_score(y_test, pred, normalize=True, sample_weight=None)
print('accuracy {}'.format(acc))

accuracy 0.533229085223


In [95]:
pred_whole_data = log.predict(whole_data)

with open('./output_ML_logistic', 'wb') as f:
    for num in pred_whole_data:
        print(num, file=f)

## Support Vector Machines

In [78]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

In [84]:
x_train.shape

(24289, 6)

In [85]:
y_train.shape

(24289, 1)

In [ ]:
# Set the parameters by cross-validation
param_grid = [
  {'C': [1, 10, 100, 1000], 'kernel': ['linear']},
  {'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001], 'kernel': ['rbf']},
 ]

clf = SVC()
clf.fit(x_train, y_train)

In [96]:
pred = clf.predict(x_test)
acc = accuracy_score(y_test, pred, normalize=True, sample_weight=None)
print('accuracy {}'.format(acc))

accuracy 0.533229085223


In [89]:
pred_whole_data = clf.predict(whole_data)

with open('./output_ML_SVM', 'wb') as f:
    for num in pred_whole_data:
        print(num, file=f)

## Neural Network

In [97]:
import keras
from keras.layers import Dense, Inpukeras.modelsas.models import Model

In [139]:
inp = Input(shape=(6,))
x = Dense(200, activation='relu')(inp)
x = Dense(200, activation='relu')(x)
x = Dense(200, activation='relu')(x)
x = Dense(3, activation='softmax')(x)

model = Model(inputs=inp, outputs=x)

In [140]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_4 (InputLayer)         (None, 6)                 0         
_________________________________________________________________
dense_10 (Dense)             (None, 200)               1400      
_________________________________________________________________
dense_11 (Dense)             (None, 200)               40200     
_________________________________________________________________
dense_12 (Dense)             (None, 200)               40200     
_________________________________________________________________
dense_13 (Dense)             (None, 3)                 603       
Total params: 82,403
Trainable params: 82,403
Non-trainable params: 0
_________________________________________________________________


In [141]:
model.compile(loss='categorical_crossentropy', optimizer='adadelta', metrics=['accuracy'])

In [142]:
from keras.utils.np_utils import to_categorical

In [143]:
y_train_cat = to_categorical(y_train, num_classes=3)

In [144]:
for i in range(0,20,2):
    print(y_train_cat[i], y_train[i])

[ 0.  0.  1.] [-1]
[ 0.  1.  0.] [1]
[ 1.  0.  0.] [0]
[ 0.  1.  0.] [1]
[ 0.  0.  1.] [-1]
[ 0.  0.  1.] [-1]
[ 0.  0.  1.] [-1]
[ 0.  0.  1.] [-1]
[ 0.  0.  1.] [-1]
[ 0.  1.  0.] [1]


In [145]:
model.fit(x_train, y_train_cat, epochs=20, validation_data=[x_test, to_categorical(y_test, num_classes=3)])

Train on 24289 samples, validate on 1279 samples
Epoch 1/20
24289/24289 [==============================] - 3s - loss: 0.9856 - acc: 0.5150 - val_loss: 0.9912 - val_acc: 0.5152
Epoch 2/20
24289/24289 [==============================] - 3s - loss: 0.9718 - acc: 0.5298 - val_loss: 0.9979 - val_acc: 0.5059
Epoch 3/20
24289/24289 [==============================] - 3s - loss: 0.9715 - acc: 0.5288 - val_loss: 0.9829 - val_acc: 0.5270
Epoch 4/20
24289/24289 [==============================] - 3s - loss: 0.9705 - acc: 0.5290 - val_loss: 0.9921 - val_acc: 0.5137
Epoch 5/20
24289/24289 [==============================] - 3s - loss: 0.9699 - acc: 0.5315 - val_loss: 0.9741 - val_acc: 0.5301
Epoch 6/20
24289/24289 [==============================] - 3s - loss: 0.9699 - acc: 0.5282 - val_loss: 0.9774 - val_acc: 0.5309
Epoch 7/20
24289/24289 [==============================] - 3s - loss: 0.9698 - acc: 0.5295 - val_loss: 0.9698 - val_acc: 0.5356
Epoch 8/20
24289/24289 [==============================] - 3s -

In [127]:
cat_classes

array([1, 1, 1, ..., 2, 1, 2])

In [146]:
cat_classes = np.argmax(model.predict(whole_data), axis=1)
pred_classes = np.zeros((np.shape(whole_data)[0],1))

for idx, cat in enumerate(cat_classes):
    if cat == 0:
        pred_classes[idx] = 0
    if cat == 1:
        pred_classes[idx] = 1
    if cat == 2:
        pred_classes[idx] = -1

pred_whole_data = pred_classes
with open('./output_ML_NN', 'wb') as f:
    for num in pred_whole_data:
        print(int(num), file=f)

In [137]:
pred_whole_data

array([[ 1.],
       [ 1.],
       [ 1.],
       ..., 
       [ 0.],
       [ 0.],
       [ 0.]])